version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
    open-pull-requests-limit: 90
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily