version: '3.1'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@ssw0rd
    ports:
      - 1433:1433