name: Assign PR data

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    name: Assign author
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Assigning author to PR
        uses: technote-space/assign-author@v1

  add-issue-link:
    name: Add issue link
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Adding issue link
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-prefix: issue-
          position: top
          resolve: true
          link-style: body

  pr-labeler:
    name: PR labeler
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}