name: Create Branch Issue

on:
  issues:
    types: [opened, assigned]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: Create issue branch
        id: create-issue-branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set PR template
        if: steps.create-issue-branch.outputs.branchName != ''
        id: template
        env:
          BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
        run: |
          branch=$BRANCH_NAME
          if [[ $branch =~ ^bugfix/ ]]; then \
            template="bug.md"; \
          elif [[ $branch =~ ^hotfix/ ]]; then \
            template="hotfix.md"; \
          elif [[ $branch =~ ^feature/ ]]; then \
            template="enhancement.md"; \
          elif [[ $branch =~ ^chore/ ]]; then \
            template="chore.md"; \
          elif [[ $branch =~ ^docs/ ]]; then \
            template="documentation.md"; \
          fi
          echo "::set-output name=template-name::$template"
          
      - name: Add PR link in comment
        uses: mshick/add-pr-comment@master
        if: steps.create-issue-branch.outputs.branchName != ''
        env:
          PULL_REQUEST_URL: ${{ format('https://github.com/{0}/compare/{1}...{2}?quick_pull=1&template={3}', github.repository, github.event.repository.default_branch, steps.create-issue-branch.outputs.branchName, steps.template.outputs.template-name) }}
          TEMPLATE: ${{ steps.template.outputs.template-name }}
        with:
          message: |
            ## Pull Request ![](https://raw.githubusercontent.com/primer/octicons/master/icons/git-pull-request-16.svg)
            [Create a pull request](${{ env.PULL_REQUEST_URL }}) for the issue branch using the `${{ env.TEMPLATE }}` template.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"