name: Delete Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Packages version'
        required: true

env:
  NUGET_SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}
  NUGET_SOURCE_API_KEY: ${{ github.token }}

jobs:
  delete_packages:
    name: Delete packages
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup dotnet core
      uses: actions/setup-dotnet@v1.9.1
      with:
        dotnet-version: 6.0.x
    
    - name: Delete Nuget Packages
      run:  |
        for f in $(find src -type f -name "*.csproj")
        do
            dotnet nuget delete $(basename $f .csproj) ${{ github.event.inputs.version }} -s ${{ env.NUGET_SOURCE_URL }} -k ${{ env.NUGET_SOURCE_API_KEY }} --non-interactive 
        done